#pragma once
#define TOTAL_INTERRUPTS 512 

#define GDT_KERNEL_CODE_SEGMENT 0x08
#define GDT_KERNEL_DATA_SEGMENT 0x10
#define GDT_USER_CODE_SEGMENT   0x1b
#define GDT_USER_DATA_SEGMENT   0x23
#define GDT_TSS                 0x28

// 100MB heap size
#define HEAP_SIZE_BYTES         104857600
#define HEAP_BLOCK_SIZE         4096
#define KHEAP_ADDRESS           0x01000000 
#define KHEAP_TABLE_ADDRESS     0x00007E00

#define SECTOR_SIZE 512

#define MAX_KEYBOARD_DRIVERS   12
#define MAX_KEYBOARD_LISTENERS 12
#define KEYBOARD_BUFFER_SIZE   1024


#define MAX_FILESYSTEMS 12
#define MAX_FILE_DESCRIPTORS 512

#define MAX_PATH 108
#define MAX_ARGS     128
#define MAX_ARG_SIZE 108

#define PROGRAM_VIRTUAL_ADDRESS 0x400000
#define USER_PROGRAM_STACK_SIZE (1024 * 16)

#define PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define PROGRAM_VIRTUAL_STACK_ADDRESS_END ((void*)(PROGRAM_VIRTUAL_STACK_ADDRESS_START - USER_PROGRAM_STACK_SIZE))
#define PROGRAM_MAX_ALLOCATIONS 1024 

#define MAX_PROCESSES 12 

#define SYSTEMCALLS_COUNT 1024

